version: '3.3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - overlay


  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'urlshortenerdb'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - overlay

volumes:
  my-db:

networks:
  overlay: